### ISSUE TITLE
Build fail trying a Small Footprint configuration [BUILD: [00:0000000003:PROGC ] Computing include file dependencies:]

### ISSUE THREAD

**Issue by microhobby** [Milek7/wince-qemu#4]
I'm selecting the Small Footprint configuration and selecting the qemu BSP. But it's failing with a weird log:

```
CEBUILD: BUILDMSG: Building platform clean due to change of project
CEBUILD: BUILDMSG: Building -c (D:\WCE700\platform\qemu)
BUILD: [Thrd:Sequence:Type  ] Message
BUILD: [00:0000000000:PROGC ] Build started with parameters: -A -c
BUILD: [00:0000000001:PROGC ] Build started in directory: D:\WCE700\platform\qemu
BUILD: [00:0000000002:PROGC ] Running passes WCEFILES0, MIDL, MC, ASN, THUNK, PRECOMPHEADER, COMPILE, LOCALIZE, RENUMBERICONIDS, RES2RES, LIB, EXPLIB, LINK, MANAGEDRESX, MANAGEDMOD, MANAGEDDLL, MANAGEDEXE, MANAGEDWIN, POSTBUILD for ARM.
BUILD: [00:0000000003:PROGC ] Computing include file dependencies:
CEBUILD: BUILDMSG: There were errors building. Check D:\WCE700\build.err

BLDDEMO: ERROR: There were errors building CEBASE.

BLDDEMO: BUILDMSG: BldDemo ended at 13:29:55.17 on Mon 03/11/2024 (exit code 1)
BuildLogs: BUILDMSG: Exiting: BldDemo1.bat  -q (result code 1).
BuildLogs: BUILDMSG: D:\WCE700\build.log
BuildLogs: BUILDMSG: D:\WCE700\build.out
BuildLogs: BUILDMSG: D:\WCE700\build.wrn
BuildLogs: BUILDMSG: D:\WCE700\build.err

```

It seems that break at this `BUILD: [00:0000000003:PROGC ] Computing include file dependencies:`.
There is no much valiable logs. @Milek7  There is some trick to configurate it to build?
Thanks in advance

**Comment by Milek7** [comment]
I'm very much confused by WinCE build system so I cannot offer much advice.
Does building with other BSP works? I don't do anything special here, after creating new solution I click in Advanced Build Commands: `Sysgen (blddemo -q)` and then `Build Current BSP and Subprojects (blddemo -qbsp)`

**Comment by microhobby** [comment]
> Does building with other BSP works? 

Yeah, the BSPTemplate is building ok. 

Even trying following your steps, I'm getting this stopping on the `BUILD: [00:0000000003:PROGC ] Computing include file dependencies:`

But ok, maybe is something in my environment.

**Comment by microhobby** [comment]
@Milek7 let me ask you for more help 😅. I was able to build the NK.bin. But now I'm stuck on how to "flat it". If you have some steps it would be helpful, thanks in advance.

**Comment by microhobby** [comment]
> But now I'm stuck on how to "flat it". 

Ok, I think that I figure out how to flat it using the `viewbin` and the `cvrtbin`.

But no success to boot it. I'm have more one question. You listed the `PL111 display (1024x600)` on the README but there is no `pl111` folder on the drivers. It should have?

**Comment by Milek7** [comment]
> there is no `pl111` folder on the drivers. It should have?

No, it uses ddi_hflat from SDK.

> But no success to boot it

Is there anything on serial output? There's possible issue with the linker, which incorrectly tries to use dynamically linked functions from coredll during early boot. I think it's issue with link order, but I don't know what's the cause of this. Instead I use this tool to patch broken addresses in compiled image. It also converts NK.bin into flat image. https://gist.github.com/Milek7/ac269a0757f7f63301110a97f46a490b This tool expects to be run in output directory and generates patched NK.bin.raw

**Comment by microhobby** [comment]
>It also converts NK.bin into flat image. https://gist.github.com/Milek7/ac269a0757f7f63301110a97f46a490b This tool expects to be run in output directory and generates patched NK.bin.raw

Interesting, this does exactly what the Microsoft tool `cvrtbin` does. But it needs the `viewbin` to get the addresses, your tool does the two tasks.

So, yeah, nothing on the serial. But probably is again some configuration or OS option that I'm toggling that is breaking stuff. 

Thanks a lot @Milek7 for the help. I will close this one since the initial issue was fixed.

**Comment by Milek7** [comment]
Conversion is done without extra files, addresses are needed to workaround the previously mentioned linker issue (I'm not sure what triggers it, you will get "patching function..." messages if it occurred).

You should get quite a lot of serial output on Checked builds. I also pushed to repository various changes I had lying around. It should now print single letter `b` during startup asm. If you don't get that you're likely misconfiguring qemu machine settings or startup address.

**Comment by Milek7** [comment]
For Small Footprint Checked build you should get this on serial. You probably want to disable KITL in Configuration Manager, otherwise it will wait for it.
```
qemu-system-arm -machine type=vexpress-a15 -m 256 -device loader,addr=0x80000000,file=NK.bin.raw,cpu-num=0 -serial stdio
bOEM
Windows CE Kernel for ARM (Thumb Enabled) Built on Jan  6 2011 at 19:31:51
ProcessorType=0c0f  Revision=0 CpuId=0x414fc0f0
OEMAddressTable = 80001558
OEMInit
NKStartup done, starting up kernel. nCpus = 1
Windows CE KernelInit
Booting Windows CE version 7.00 for (ARM)
OEMGetExtensionDRAM
Memory Configuring: Total pages: 65078, Filesystem pages = 32539
Booting kernel with clean memory configuration:
Total Memory Sections:1
[0] (static): start: 801c6000, extension/attributes: 00040000, length: 0fe36000
Scheduling the first thread.
PID:00400002 TID:00410002 PGPOOL: Reserved 768 pages for Loader pool
PID:00400002 TID:00410002 PGPOOL: Reserved 256 pages for File pool
PID:00400002 TID:00410002 OSAXST0: Platform Name = Pocket PC
PID:00400002 TID:00410002 OSAXST1: >>> Loading Module 'kd.dll' (0x92801DB0) at address 0xEFFE0000-0xEFFF9000 in Process 'NK.EXE' (0x801A8A60)
PID:00400002 TID:00410002 KD: Starting kernel debugger software probe (KdStub) - KD API version 27
PID:00400002 TID:00410002 OSAXST1: >>> Loading Module 'NK.EXE' (0x801A8A60) at address 0x80000000-0x80005000 in Process 'NK.EXE' (0x801A8A60)
PID:00400002 TID:00500002 Filesys doesn't exist, no app started
```

**Comment by microhobby** [comment]
@Milek7 holy molly macaroni! So, the stuff is more complicated than it seems. Nice, I was able to have the serial output now, thanks a lot!

**Comment by zhangzhen1127** [comment]
@microhobby CLEANOS.BAT: BUILDMSG: Cleaning platform directory C:\WINCE700\OSDesigns\sy\Wince700\qemu_ARMV7_Retail\cesysgen\platform\qemu\target
CLEANOS.BAT: BUILDMSG: Cleaning platform directory C:\WINCE700\OSDesigns\sy\Wince700\qemu_ARMV7_Retail\cesysgen\platform\qemu\lib
CLEANOS.BAT: BUILDMSG: Removing C:\WINCE700\OSDesigns\sy\Wince700\qemu_ARMV7_Retail\cesysgen\platform\*.bif
CEBUILD: BUILDMSG: Building platform clean due to change of project
CEBUILD: BUILDMSG: Building -c (C:\WINCE700\platform\qemu)
BUILD: [Thrd:Sequence:Type  ] Message
BUILD: [00:0000000000:PROGC ] Build started with parameters: -A -c
BUILD: [00:0000000001:PROGC ] Build started in directory: C:\WINCE700\platform\QEMU
BUILD: [00:0000000002:PROGC ] Running passes WCEFILES0, MIDL, MC, ASN, THUNK, PRECOMPHEADER, COMPILE, LOCALIZE, RENUMBERICONIDS, RES2RES, LIB, EXPLIB, LINK, MANAGEDRESX, MANAGEDMOD, MANAGEDDLL, MANAGEDEXE, MANAGEDWIN, POSTBUILD for ARM.
BUILD: [00:0000000003:PROGC ] Computing include file dependencies:
CEBUILD: BUILDMSG: There were errors building. Check C:\WINCE700\build.err

BLDDEMO: ERROR: There were errors building CEBASE.
Hello, I also met the same problem, I would like to ask you how to solve, thank you！

**Comment by zhangzhen1127** [comment]
> @Milek7 let me ask you for more help 😅. I was able to build the NK.bin. But now I'm stuck on how to "flat it". If you have some steps it would be helpful, thanks in advance.
Hello, I'm very sorry to bother you, I see you have solved this problem, I also met the same problem, could you please tell me how to solve it, thank you
CEBUILD: BUILDMSG: Building  (C:\WINCE700\platform\qemu)
BUILD: [00:0000000000:PROGC ] Build started with parameters: -A
BUILD: [00:0000000001:PROGC ] Build started in directory: C:\WINCE700\platform\qemu
BUILD: [00:0000000002:PROGC ] Running passes WCEFILES0, MIDL, MC, ASN, THUNK, PRECOMPHEADER, COMPILE, LOCALIZE, RENUMBERICONIDS, RES2RES, LIB, EXPLIB, LINK, MANAGEDRESX, MANAGEDMOD, MANAGEDDLL, MANAGEDEXE, MANAGEDWIN, POSTBUILD for ARM.
BUILD: [00:0000000003:PROGC ] Computing include file dependencies:
CEBUILD: BUILDMSG: There were errors building. Check C:\WINCE700\build.err
BLDDEMO: ERROR: There were errors building CEBASE. {log="C:\WINCE700\build.log(33587)"}
BLDDEMO: BUILDMSG: BldDemo ended at  2:11:52.16 on 2024/08/12 周一 (exit code 1)
BuildLogs: BUILDMSG: Exiting: BldDemo1.bat  -q (result code 1).
BuildLogs: BUILDMSG: C:\WINCE700\build.log
BuildLogs: BUILDMSG: C:\WINCE700\build.out
BuildLogs: BUILDMSG: C:\WINCE700\build.wrn
BuildLogs: BUILDMSG: C:\WINCE700\build.err
dabao - 1 error(s), 194 warning(s)

**Comment by Milek7** [comment]
I previously posted an utility that I'm using: https://gist.github.com/Milek7/ac269a0757f7f63301110a97f46a490b

**Comment by zhangzhen1127** [comment]
@microhobby 


    @Milek7 let me ask you for more help 😅. I was able to build the NK.bin. But now I'm stuck on how to "flat it". If you have some steps it would be helpful, thanks in advance.
    Hello, I'm very sorry to bother you, I see you have solved this problem, I also met the same problem, could you please tell me how to solve it, thank you
    CEBUILD: BUILDMSG: Building (C:\WINCE700\platform\qemu)
    BUILD: [00:0000000000:PROGC ] Build started with parameters: -A
    BUILD: [00:0000000001:PROGC ] Build started in directory: C:\WINCE700\platform\qemu
    BUILD: [00:0000000002:PROGC ] Running passes WCEFILES0, MIDL, MC, ASN, THUNK, PRECOMPHEADER, COMPILE, LOCALIZE, RENUMBERICONIDS, RES2RES, LIB, EXPLIB, LINK, MANAGEDRESX, MANAGEDMOD, MANAGEDDLL, MANAGEDEXE, MANAGEDWIN, POSTBUILD for ARM.
    BUILD: [00:0000000003:PROGC ] Computing include file dependencies:
    CEBUILD: BUILDMSG: There were errors building. Check C:\WINCE700\build.err
    BLDDEMO: ERROR: There were errors building CEBASE. {log="C:\WINCE700\build.log(33587)"}
    BLDDEMO: BUILDMSG: BldDemo ended at 2:11:52.16 on 2024/08/12 周一 (exit code 1)
    BuildLogs: BUILDMSG: Exiting: BldDemo1.bat -q (result code 1).
    BuildLogs: BUILDMSG: C:\WINCE700\build.log
    BuildLogs: BUILDMSG: C:\WINCE700\build.out
    BuildLogs: BUILDMSG: C:\WINCE700\build.wrn
    BuildLogs: BUILDMSG: C:\WINCE700\build.err
    dabao - 1 error(s), 194 warning(s)
