### ISSUE TITLE
About raw file generation problem

### ISSUE THREAD

**Issue by zhangzhen1127** [Milek7/wince-qemu#5]
Hello, may I ask how to generate your nk.bin.load -0x800010c0.raw file? I generated NK.bin after compiling with vs, and nk.nb0 file after unpackNK.bin.load-0x800010c0.rawing. How should I realize if I want to add network module?

**Comment by Milek7** [comment]
PB tools should theoretically work for converting the file, but I use this tool: https://gist.github.com/Milek7/ac269a0757f7f63301110a97f46a490b

For network you would need to have appropiate driver, either write virtio-net NDIS driver (not sure how much code from NT driver could be reused), or add PCI support and reuse existing CE driver.

**Comment by zhangzhen1127** [comment]
Thank you very much for your reply. I will try again. Could you give me a complete project file about wince-qemu? I reported some problems in the boot section when generating nk.bin, thank you very much!
